name = "TreeFun"
uuid = "2a96cbe9-462c-49af-8a56-5179987763fb"
authors = ["lxvm <lorenzo@vanmunoz.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
